"""Report generation in JSON, Markdown, and HTML formats."""

from __future__ import annotations

import json
import html as html_lib
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, TYPE_CHECKING

if TYPE_CHECKING:
    from osintrecon.core.config import Config
    from osintrecon.core.engine import ReconResult


class ReportGenerator:
    """Generates investigation reports in multiple formats.

    Args:
        config: Framework configuration (used for ``output_dir``).
    """

    def __init__(self, config: "Config") -> None:
        self.config = config

    def generate(self, result: "ReconResult", fmt: str = "json") -> str:
        """Generate a report string.

        Args:
            result: The :class:`ReconResult` to serialize.
            fmt: ``'json'``, ``'markdown'``, or ``'html'``.

        Returns:
            The formatted report as a string.
        """
        dispatch = {
            "json": self._to_json,
            "markdown": self._to_markdown,
            "html": self._to_html,
        }
        handler = dispatch.get(fmt)
        if handler is None:
            raise ValueError(f"Unknown format: {fmt!r}. Choose from json, markdown, html.")
        return handler(result)

    def save(self, result: "ReconResult", fmt: str = "json") -> Path:
        """Generate a report and write it to ``config.output_dir``.

        Returns:
            The :class:`Path` to the written file.
        """
        ext = {"json": "json", "markdown": "md", "html": "html"}[fmt]
        out_dir = Path(self.config.output_dir)
        out_dir.mkdir(parents=True, exist_ok=True)

        ts = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
        safe_target = result.target.replace("/", "_").replace("\\", "_").replace("@", "_at_")
        filename = f"recon_{safe_target}_{ts}.{ext}"
        path = out_dir / filename

        content = self.generate(result, fmt)
        path.write_text(content, encoding="utf-8")
        return path

    # ------------------------------------------------------------------
    # Formatters
    # ------------------------------------------------------------------

    @staticmethod
    def _to_json(result: "ReconResult") -> str:
        return json.dumps(result.to_dict(), indent=2, default=str)

    @staticmethod
    def _to_markdown(result: "ReconResult") -> str:
        lines: list[str] = []
        lines.append(f"# OSINT Recon Report")
        lines.append("")
        lines.append(f"**Target:** `{result.target}`  ")
        lines.append(f"**Type:** {result.target_type}  ")
        lines.append(f"**Duration:** {result.duration:.2f}s  ")
        started = datetime.fromtimestamp(result.started_at, tz=timezone.utc)
        lines.append(f"**Date:** {started.strftime('%Y-%m-%d %H:%M:%S UTC')}  ")
        lines.append("")
        lines.append("---")
        lines.append("")

        for module, data in result.findings.items():
            lines.append(f"## {module.replace('_', ' ').title()}")
            lines.append("")
            if isinstance(data, list):
                for item in data:
                    if isinstance(item, dict):
                        for k, v in item.items():
                            lines.append(f"- **{k}:** {v}")
                        lines.append("")
                    else:
                        lines.append(f"- {item}")
            elif isinstance(data, dict):
                for k, v in data.items():
                    lines.append(f"- **{k}:** {v}")
            else:
                lines.append(str(data))
            lines.append("")

        if result.errors:
            lines.append("## Errors")
            lines.append("")
            for mod, err in result.errors.items():
                lines.append(f"- **{mod}:** {err}")
            lines.append("")

        lines.append("---")
        lines.append("*Generated by OSINTRecon*")
        return "\n".join(lines)

    @staticmethod
    def _to_html(result: "ReconResult") -> str:
        esc = html_lib.escape

        started = datetime.fromtimestamp(result.started_at, tz=timezone.utc)

        def _render_value(v: Any) -> str:
            if isinstance(v, dict):
                items = "".join(
                    f"<li><strong>{esc(str(k))}:</strong> {esc(str(val))}</li>"
                    for k, val in v.items()
                )
                return f"<ul>{items}</ul>"
            if isinstance(v, list):
                items = "".join(f"<li>{esc(str(i))}</li>" for i in v)
                return f"<ul>{items}</ul>"
            return esc(str(v))

        sections = ""
        for module, data in result.findings.items():
            title = module.replace("_", " ").title()
            body = _render_value(data)
            sections += f"<section><h2>{esc(title)}</h2>{body}</section>\n"

        errors_html = ""
        if result.errors:
            err_items = "".join(
                f"<li><strong>{esc(m)}:</strong> {esc(e)}</li>"
                for m, e in result.errors.items()
            )
            errors_html = f"<section><h2>Errors</h2><ul>{err_items}</ul></section>"

        return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>OSINT Recon Report - {esc(result.target)}</title>
<style>
  body {{ font-family: 'Segoe UI', Tahoma, sans-serif; max-width: 900px; margin: 2rem auto; background: #0d1117; color: #c9d1d9; padding: 1rem; }}
  h1 {{ color: #58a6ff; border-bottom: 1px solid #30363d; padding-bottom: .5rem; }}
  h2 {{ color: #79c0ff; }}
  code {{ background: #161b22; padding: 2px 6px; border-radius: 3px; }}
  ul {{ list-style: disc; padding-left: 1.5rem; }}
  section {{ background: #161b22; border: 1px solid #30363d; border-radius: 6px; padding: 1rem; margin-bottom: 1rem; }}
  .meta {{ color: #8b949e; }}
  strong {{ color: #e6edf3; }}
</style>
</head>
<body>
<h1>OSINT Recon Report</h1>
<p class="meta">
  <strong>Target:</strong> <code>{esc(result.target)}</code> |
  <strong>Type:</strong> {esc(result.target_type)} |
  <strong>Duration:</strong> {result.duration:.2f}s |
  <strong>Date:</strong> {started.strftime('%Y-%m-%d %H:%M:%S UTC')}
</p>
{sections}
{errors_html}
<hr>
<p class="meta"><em>Generated by OSINTRecon</em></p>
</body>
</html>"""
